;; -*- mode: eask; lexical-binding: t -*-

(package "dired-hacks"
         "0.0.1"
         "Collection of useful dired additions")

(website-url "")
(keywords "files")

(package-file "dired-hacks.el")

(files
 "dired-avfs.el"
 "dired-collapse.el"
 "dired-columns.el"
 "dired-filter.el"
 "dired-hacks.el"
 "dired-hacks-utils.el"
 "dired-list.el"
 "dired-narrow.el"
 "dired-open.el"
 "dired-rainbow.el"
 "dired-ranger.el"
 "dired-subtree.el"
 "dired-tagsistant.el"
 "dired-ui.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "dash")
(depends-on "eimp")
(depends-on "f")
(depends-on "assess")

(development
 (depends-on "buttercup"))
